server:
  port: 80

spring:
  datasource:
    driverClassName: org.h2.Driver
    jdbcUrl: jdbc:h2:mem:h2db
    username: sa
    password:
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console